---
kind: pipeline
name: test

steps:
- name: test
  image: node:22
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN
  commands:
    - npm ci
    - npm test

trigger:
  event: [push]

---
kind: pipeline
name: tag
depends_on: [test]

clone:
  depth: 100

steps:
- name: release
  image: livingdocs/semantic-release:v3.0.2
  environment:
    GH_TOKEN:
      from_secret: GH_TOKEN

trigger:
  event: [push]
---
kind: signature
hmac: 378773d83c6dab7b8b05079507832fd2309683368700afcd7f7755c164e9649a

...
